name: tetris
version: 0.1.0
summary: Tetris Game
description: A good looking tetris game to enjoy anytime!

confinement: strict
base: core18
grade: stable

slots:
  dbus-tetris: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.tetris # adjust accordingly to your app name and
    
apps:
  tetris:
    command: tetris
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-tetris
parts:
  tetris:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
