name: tetris
version: 0.1.3
summary: Tetris Game
description: A good looking tetris game to enjoy anytime!

confinement: strict
base: core18
grade: stable

apps:
  tetris:
    command: bin/tetris
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs: [home]

parts:
  tetris:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application